version: "3.8"

services:
  db:
    image: postgres
    container_name: github-notifier-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:alpine
    container_name: github-notifier-reverse-proxy
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: http localhost:8080
    network_mode: "host"

volumes:
  pgdata:
